### ISSUE TITLE
[Subtask]:  We need to perform regression testing on historical issues.

### ISSUE THREAD

**Issue by Aireed** [apache/amoro#1411]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?q=is%3Aissue) and found no similar issues.

### Description

Fatal
------
**Mixed format**
- [x] https://github.com/NetEase/arctic/pull/814 @shidayang  Covered
- [x] https://github.com/NetEase/arctic/pull/846 @shidayang Discard
- [x] https://github.com/NetEase/arctic/pull/848 @shidayang Discard
- [x] https://github.com/NetEase/arctic/pull/872 @shidayang Discard
- [x] https://github.com/NetEase/arctic/pull/892 @shidayang Discard
- [x] https://github.com/NetEase/arctic/pull/894 @shidayang Discard
- [x] https://github.com/NetEase/arctic/pull/921 @wangtaohz Discard
- [x] https://github.com/NetEase/arctic/pull/968 @HuangFru  discard
- [x] https://github.com/NetEase/arctic/pull/939 @shidayang Covered
- [x] https://github.com/NetEase/arctic/pull/986 @wangtaohz Merged
- [x] https://github.com/NetEase/arctic/pull/1010 @wangtaohz Merged
- [x] https://github.com/NetEase/arctic/pull/1022 @shidayang  Discard
- [x] https://github.com/NetEase/arctic/pull/1046 @shidayang Covered
- [x] https://github.com/NetEase/arctic/pull/1058 @wangtaohz Covered
- [x] https://github.com/NetEase/arctic/pull/1064 @wangtaohz Covered
- [x] https://github.com/NetEase/arctic/pull/1071 @wangtaohz Discard
- [x] https://github.com/NetEase/arctic/pull/1072 @shidayang Covered
- [x] https://github.com/NetEase/arctic/pull/1087 @wangtaohz Covered
- [x] https://github.com/NetEase/arctic/pull/1122 @HuangFru Covered
- [x] https://github.com/NetEase/arctic/pull/1125 @wangtaohz Covered
- [x] https://github.com/NetEase/arctic/pull/1151 @wangtaohz Covered
- [x] https://github.com/NetEase/arctic/pull/1296 @HuangFru Covered
- [x] https://github.com/NetEase/arctic/pull/1320 @shidayang Discard
- [x] https://github.com/NetEase/arctic/pull/1324 @shidayang Discard
- [x] https://github.com/NetEase/arctic/pull/1348  @shidayang
- [x] https://github.com/NetEase/arctic/pull/1351  @shidayang
- [ ] https://github.com/NetEase/arctic/pull/1370  @hellojinsilei 
- [x] https://github.com/NetEase/arctic/pull/1371  @wangtaohz Covered
- [ ] https://github.com/NetEase/arctic/pull/1376  @Aireed 
- [ ] https://github.com/NetEase/arctic/pull/1398  @baiyangtx 
- [ ] https://github.com/NetEase/arctic/pull/1405  @hellojinsilei  

**Iceberg format**
- [x] https://github.com/NetEase/arctic/pull/923
- [x] https://github.com/NetEase/arctic/pull/1101
- [x] https://github.com/NetEase/arctic/pull/1390 @wangtaohz Merged

**Common**
- [x] https://github.com/NetEase/arctic/pull/823
- [x] https://github.com/NetEase/arctic/pull/878 @HuangFru Covered
- [x] https://github.com/NetEase/arctic/pull/893 @HuangFru Covered
- [x] https://github.com/NetEase/arctic/pull/949
- [x] https://github.com/NetEase/arctic/pull/963
- [x] https://github.com/NetEase/arctic/pull/993 @shidayang Covered
- [x] #971 shidayang
- [x] https://github.com/NetEase/arctic/pull/1086
- [x] https://github.com/NetEase/arctic/pull/1094
- [x] https://github.com/NetEase/arctic/pull/1099
- [x] https://github.com/NetEase/arctic/pull/1104 @shidayang Covered
- [x] https://github.com/NetEase/arctic/pull/1168 @shidayang Discard
- [x] https://github.com/NetEase/arctic/pull/1178 @HuangFru Covered
- [x] https://github.com/NetEase/arctic/pull/1181 @HuangFru  Covered
- [x] https://github.com/NetEase/arctic/pull/1193 @HuangFru Covered
- [x] https://github.com/NetEase/arctic/pull/1248 @shidayang Covered
- [x] https://github.com/NetEase/arctic/pull/1292 @HuangFru Discard
- [x] https://github.com/NetEase/arctic/pull/1294 @HuangFru Covered
- [ ] https://github.com/NetEase/arctic/pull/1345  @hellojinsilei 
- [ ] https://github.com/NetEase/arctic/pull/1379  @hameizi 
- [ ] https://github.com/NetEase/arctic/pull/1391  @hellojinsilei  
- [ ] https://github.com/NetEase/arctic/pull/1393  @YesOrNo828 
- [x] https://github.com/NetEase/arctic/pull/1395  @zhoujinsong 
- [x] https://github.com/NetEase/arctic/pull/1396  @wangtaohz Merged
- [ ] https://github.com/NetEase/arctic/pull/1409  @hellojinsilei 
- [ ] https://github.com/NetEase/arctic/pull/1413  @lklhdu 
- [ ] https://github.com/NetEase/arctic/pull/1414  @hellojinsilei 

minor
--------
- [x] https://github.com/NetEase/arctic/pull/823 @hameizi 
- [x] https://github.com/NetEase/arctic/pull/825 @hameizi 
- [x] https://github.com/NetEase/arctic/pull/837 @hameizi 
- [x] https://github.com/NetEase/arctic/pull/909 @hellojinsilei 
- [x] https://github.com/NetEase/arctic/pull/1264 @hellojinsilei 
- [x] https://github.com/NetEase/arctic/pull/1222 @shidayang @Discard

deprecated
--------
- [x] https://github.com/NetEase/arctic/pull/1014
- [x] https://github.com/NetEase/arctic/pull/1100

### Parent issue

https://github.com/NetEase/arctic/issues/1372

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
