### ISSUE TITLE
[Improvement]:  support iceberg 1.3.X and support spark 3.4.X

### ISSUE THREAD

**Issue by BsoBird** [apache/amoro#1554]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

 support iceberg 1.3.X and support spark 3.4.X

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Subtasks

- [x] #1668 
- [ ] #1669 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhoujinsong** [comment]
Thank you very much for bringing this up. The community has been working hard to keep up with support for new versions of formats and engines, and we will include this in our roadmap for future versions.


However, to avoid affecting your use before we upgrade the version, I need to remind you that if you are using the Iceberg format, the current version of Iceberg that Arctic relies on, as well as the Spark version, do not affect your use of Arctic to manage and automatically optimizing your Iceberg tables.

**Comment by BsoBird** [comment]
you mean:

**Comment by baiyangtx** [comment]
Thank you for raising the issue. Could you please share what your actual needs are? Do you want to use Arctic with Spark 3.4?

**Comment by shidayang** [comment]
I believe upgrading to Iceberg 1.3.0 is a natural behavior, and we should try our best to ensure that the Iceberg version in Arctic is relatively up-to-date. However, I think Spark 3.4 is worth discussing.

**Comment by BsoBird** [comment]
@shidayang @baiyangtx @zhoujinsong 
ICEBERG 1.3.0 fixes some major bugs. Some features need to be used with SPARK 3.4.
example:
https://github.com/apache/iceberg/issues/7431

**Comment by shidayang** [comment]
> @shidayang @baiyangtx @zhoujinsong ICEBERG 1.3.0 fixes some major bugs. Some features need to be used with SPARK 3.4. example: [apache/iceberg#7431](https://github.com/apache/iceberg/issues/7431)

I agree to upgrade the Iceberg version to 1.3.0.

**Comment by baiyangtx** [comment]
> @shidayang @baiyangtx @zhoujinsong ICEBERG 1.3.0 fixes some major bugs. Some features need to be used with SPARK 3.4. example: [apache/iceberg#7431](https://github.com/apache/iceberg/issues/7431)

I agree with it.

Would you be willing to submit a PR to do this?

**Comment by caoyu-boy** [comment]
! [image](https://github.com/NetEase/arctic/assets/79634622/09a96434-792e-4164-9867-8e32c8e2e122)
 I'm following this issue, do we still need to upgrade iceberg 1.3. and support flink1.5/1.6.1.7 ？
But I noticed that after iceberg-core1.3.0, the minimum version of flink is 1.15.
Do we need to remove the support of arctic for flink before 1.15?

**Comment by wangtaohz** [comment]
In order to finally get the ball rolling, I would like to split this issue into 2 subtasks.
- subtask-1: upgrade iceberg version to 1.3.0
- subtask-2: support Spark 3.4.x

and create another issue to no longer support lower versions of Flink.

Now we can start subTask-1 on the `master` branch, as the code for version 0.5.0 is relatively stable now, then we can support Iceberg 1.3.0 before 0.6.0 (maybe 0.5.1).

Also, I have done some testing under Iceberg 1.3.0, and I believe that only a few API changes are needed to complete the upgrade. 

@BsoBird Would you like to submit a PR to deal with subtask-1 and upgrade Iceberg to 1.3.0? I would be glad to review it!

**Comment by czy006** [comment]
#3084 Spark 3.4.X
