### ISSUE TITLE
[Subtask]: Improve the unit tests for module Flink

### ISSUE THREAD

**Issue by lklhdu** [apache/amoro#1598]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Unit testing is an important part of ensuring the quality of open-source projects and we need to improve unit test cases in Flink module.

### Parent issue

#937 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Subtasks

- [ ] #1364 
- [x] #1440 
- [x] #1596 
- [ ] #1597 
- [x] #696 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
