### ISSUE TITLE
[Improvement]: Rename project from `Arctic` to `Amoro`

### ISSUE THREAD

**Issue by zhoujinsong** [apache/amoro#1744]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

The current project name Arctic was very popular among community members, but as we were planning for the project's long-term development, we found that:

- There was a risk of conflict with the trademarks of some other software. 
- The name Arctic was inspired more by the great data lake project Apache Iceberg, as Arctic began to adapt to more data lake table formats, the name Arctic seemed less suitable.
 
Therefore, we wanted to give the project a new name that was cute and easy to spread and we found `Amaura` from the Japanese anime "Pokemon". Amaura is a small and adorable pocket monster born from ice and snow, with unlimited evolution potential. Although the spelling of Amaura is concise enough, we thought it was a bit redundant. Therefore, we will use `Amoro` as the abbreviation to avoid potential trademark conflicts.

Besides, we design a new logo for Amoro:
![image](https://github.com/NetEase/arctic/assets/7424437/ec0a9ea1-9904-430b-b73b-a0e6974b1ca8)

### How should we improve?

Changing the project name is a complex process, and we need to accomplish the following tasks:

1. Change the artifact id in `pom` files.
2. Change the content in `README.md`.
3. Change the project name and logo in Dashboard.
4. Modify the project name and logo in the user document.
5. Change the package name of classes.
6. Change the class names
7. Change some variable names using the old project name.

As version `0.5.0` will be the first version using the new name. we should complete tasks 1-4 before releasing 0.5.0.
Tasks 5-7 may cause compatibility issues with older versions, so they will be finished later.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Subtasks

- [x] #1756 
- [x] #1759 
- [x] #1791 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
