### ISSUE TITLE
[Improvement]: Optimize the dependency management for the Amoro project

### ISSUE THREAD

**Issue by zhoujinsong** [apache/amoro#2012]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

I would like to propose an effort to optimize the dependency management for the Amoro project. As the project has grown, managing its dependencies has become increasingly complex and time-consuming. I believe we can make improvements to streamline this process and ensure our dependencies are up to date and secure.

### How should we improve?

To accomplish this, I propose the following steps:

- Check the dependency relationships in the project and remove unused dependencies. This can reduce build time and the size of the package after building.
- Remove dependencies with unfriendly licenses to ensure that the project complies with the requirements of the Apache License 2.0.
- Keep only direct dependencies in the project, without specifying indirect dependencies. This can simplify the pom.xml file and reduce maintenance work.
- Introduce dependency management plugins that can automatically update dependency versions to ensure that the dependencies used in the project are the latest and stable.

I think this effort will benefit the project in the long run and make it easier for current and future contributors to work on the project. I welcome any feedback or suggestions on how we can improve the dependency management for the Amoro project.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Subtasks

- [x] #2036 
- [x] #2037 
- [x] #2030
- [x] #2578 
- [ ] #2583 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
