### ISSUE TITLE
[Improvement]: Add UT for dashboard api

### ISSUE THREAD

**Issue by shidayang** [apache/amoro#2119]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Currently, all dashboard APIs do not have unit tests, and we hope for two improvements.
 First, modify the code of the APIs to make it easy to write unit tests. 
Second, add unit tests to various modules.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Subtasks

- [ ] #2120 
- [ ] #2121 
- [ ] #2122 
- [ ] #2123 
- [ ] #2124 
- [ ] #2125 
- [ ] #2126 
- [ ] #2127 
- [ ] #2128 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Jiabao-Sun** [comment]
Hi @GOODBOY008, can I help complete these tasks?

**Comment by GOODBOY008** [comment]
@Jiabao-Sun It's very well to collaborate with you, You can comment at subtask and I will assign it to you.
