### ISSUE TITLE
[Improvement]: Bump up the versions of Hadoop and Hive to the latest versions

### ISSUE THREAD

**Issue by zhoujinsong** [apache/amoro#2564]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Amoro should support multiple versions of Hadoop and Hive clusters as much as possible, allowing users to specify versions during build time, but our default version should remain the latest.

### How should we improve?

Bump up version to:

- Hadoop2: 2.10.2
- Hadoop3: 3.3.6
- Hive2: 2.3.9
- Hive3: 3.1.3

references:

- https://hadoop.apache.org/releases.html
- https://hive.apache.org/general/downloads/

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Subtasks

- [ ] #2574 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zabetak** [comment]
There is also Hive-4.0.0-beta-1 available and soon there will be a GA.

**Comment by czy006** [comment]
I saw that hive 4.0 has some new support and features for iceberg. After the introduction, we need to integrate this part. If you are interested, I suggest that we can discuss and exchange it. @zabetak
