### ISSUE TITLE
[Improvement]: code uniformly name to amoro

### ISSUE THREAD

**Issue by czy006** [apache/amoro#2738]
### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Currently, Amoro has been contributed to the Apache Incubator. In the past, some package names were still Arctic. We need to unify them into amoro. This includes renaming packages, changing the front end, and renaming and cleaning some expired fields.

### How should we improve?

- change package to org.apache.amoro
- helm chart replace to org.apache.amoro
- properties replace to amoro

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Subtasks

- [x] #2226 
- [x] #2717 
- [x] #2727
- [x] #2745 
- [x] #2750 
- [x] #2756
- [x] #2757
- [x] #2771 
- [x] #2801 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
