### ISSUE TITLE
[Improvement]: Optimizing the RestAPI efficiency

### ISSUE THREAD

**Issue by klion26** [apache/amoro#3064]
### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

This is an umbrella issue tracking the optimizing for RestApi efficiency

### How should we improve?

details go to the subtasks

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Subtasks

- [ ] #2893 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
