### ISSUE TITLE
[Improvement]: Upgrade to iceberg 1.6.0

### ISSUE THREAD

**Issue by czy006** [apache/amoro#3084]
### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Upgrade to [iceberg 1.6.0](https://iceberg.apache.org/releases/#160-release)
This is the last version support jdk8

### How should we improve?

- upgrade flink mixed formate base flink version 1.18
- upgrade iceberg dependency 1.6.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Subtasks

- [ ] #1669 
- [x] #2905

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by czy006** [comment]
discuss e-mail [https ://lists.apache.org/thread/1crbstg7prjxz8xokd7dtj1o5mgv1034](https://lists.apache.org/thread/1crbstg7prjxz8xokd7dtj1o5mgv1034)
