### ISSUE TITLE
[Improvement]: Support sorting and filtering for table  UI on AMS Dashboard

### ISSUE THREAD

**Issue by zhoujinsong** [apache/amoro#885]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

There are many table UI on AMS Dashboard.
We should support sorting and filtering operations to improve user experience.

### How should we improve?

Add sorting and filtering operations for table UI on AMS Dashboard.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Subtasks

- [x] #2149 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhoujinsong** [comment]
I will list the specific pages that need to be improvement later.

**Comment by XBaith** [comment]
Hi @zhoujinsong @zhangmo8 , should we consider supporting this feature now?

**Comment by zhangmo8** [comment]
When the performance of the server is sufficient, I think it can be considered, but the relevant interactions need to be discussed in advance.
