### ISSUE TITLE
[Improvement]: Improve unit test cases for Amoro project

### ISSUE THREAD

**Issue by zhoujinsong** [apache/amoro#937]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Unit testing is an important part of ensuring the quality of open-source projects.
But the unit test cases for Arctic project seems unsatisfactory for now, as below:

- Incomplete unit test cases, lacking test cases for completion scenarios and parameters, especially for exception scenarios
- Test case execution is not efficient enough, easy to block on Github
- The quality of the test code is not high enough and each module has its own test framework

### How should we improve?

We should improve the quality of unit testing in several ways to achieve the final goal of improving the quality of the project:

- Unifying the testing framework for each module
- Develop quality standards for test code and provide samples for developers to follow
- Complementary test cases for each module
- Add some end-to-end test cases.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Subtasks

- [x] #941 
- [ ]  #1160
- [x] #1382 
- [x] #1598  

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Aireed** [comment]
for there is still a lot of work to do,  i remove it from 0.5.0 milestone.
